apiVersion: v1
kind: Pod
metadata:
  name: writer-pod
spec:
  containers:
  - name: my-container
    image: nginx:alpine
    volumeMounts:
    - mountPath: "/data"
      name: my-storage
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-data-claim
