---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.pikachu.com
  resources:
  - pikachus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.pikachu.com
  resources:
  - pikachus/finalizers
  verbs:
  - update
- apiGroups:
  - core.pikachu.com
  resources:
  - pikachus/status
  verbs:
  - get
  - patch
  - update
