apiVersion: v1
kind: Pod
metadata:
  name: caged-pod
spec:
  containers:
  - name: java-app-simulator
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
