services:
  nginx:
    image: nginx:alpine
    container_name: auditor-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend
    container_name: auditor-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    container_name: auditor-frontend
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: auditor-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: auditor-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:latest
    container_name: auditor-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
      - loki

  # 📦 THE BLACK BOX: Loki (Log Database)
  loki:
    image: grafana/loki:latest
    container_name: auditor-loki
    volumes:
      - ./logging/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  # 🕵️ THE AGENT: Promtail (Log Collector)
  promtail:
    image: grafana/promtail:latest
    container_name: auditor-promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logging/promtail-config.yaml:/etc/promtail/config.yml
    depends_on:
      - loki
