apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: my-app
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: db-passwords
          key: username
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-passwords
          key: password
