apiVersion: v1
kind: Pod
metadata:
  name: my-init-pod
spec:
  initContainers:
  - name: the-setup-crew
    image: busybox
    command: 
      - /bin/sh
      - -c
      - echo "Setup Crew is working..."; sleep 15; echo "Setup Complete!"
  containers:
  - name: the-main-app
    image: busybox
    command: 
      - /bin/sh
      - -c
      - echo "Main app is finally online!"; sleep 3600
