apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-pilot-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auto-web
  template:
    metadata:
      labels:
        app: auto-web
    spec:
      containers:
      - name: nginx
        image: pikachu003/auto-web:v1
