apiVersion: v1
kind: Service
metadata:
  name: db-network
spec:
  clusterIP: None
  selector:
    app: secure-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pikachu-db
spec:
  serviceName: "db-network"
  replicas: 3
  selector:
    matchLabels:
      app: secure-db
  template:
    metadata:
      labels:
        app: secure-db
    spec:
      containers:
      - name: database-simulator
        image: nginx
