apiVersion: v1
kind: Pod
metadata:
  name: special-ops-pod
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "special-ops"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
