apiVersion: v1
kind: Pod
metadata:
  name: slow-starter-pod
spec:
  containers:
  - name: my-slow-app
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 20; touch /tmp/ready; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 2
      periodSeconds: 5
